In [1]:
import numpy as np

def cholesky_decomposition(A):
    """
    Perform Cholesky Decomposition on a symmetric, positive-definite matrix A.
    The result is a lower triangular matrix L such that A = L * L^T.

    Parameters:
    A : ndarray
        A symmetric, positive-definite matrix.

    Returns:
    L : ndarray
        The lower triangular matrix such that A = L * L^T.
    """
    n = A.shape[0]
    L = np.zeros_like(A)

    for i in range(n):
        for j in range(i + 1):
            if i == j:
                # Calculate diagonal elements
                L[i, j] = np.sqrt(A[i, i] - np.sum(L[i, :j] ** 2))
            else:
                # Calculate off-diagonal elements
                L[i, j] = (A[i, j] - np.sum(L[i, :j] * L[j, :j])) / L[j, j]
                
    return L

# Example usage:
A = np.array([[4, 12, -16],
              [12, 37, -43],
              [-16, -43, 98]])

L = cholesky_decomposition(A)
print("Lower triangular matrix L:")
print(L)

# Verify the decomposition: A should be approximately equal to L * L^T
print("\nCheck: L * L^T")
print(np.dot(L, L.T))


Lower triangular matrix L:
[[ 2  0  0]
 [ 6  1  0]
 [-8  5  3]]

Check: L * L^T
[[  4  12 -16]
 [ 12  37 -43]
 [-16 -43  98]]
